import type { Quest } from './types'

export const SEED_QUESTS: Quest[] = [
  {
    id: 'q-wolves',
    title: 'Wolves at the Mill',
    region: 'Whispering Woods',
    giver: 'Miller Hanne',
    difficulty: 'easy',
    reward: 40,
    status: 'active',
    steps: ['Talk to Hanne at the mill', 'Track the pack north', 'Drive off the alpha'],
    resetCount: 0,
  },
  {
    id: 'q-dragon',
    title: 'The Ember Wyrm',
    region: 'Ashen Peaks',
    giver: 'Captain Roderic',
    difficulty: 'legendary',
    reward: 1200,
    status: 'available',
    steps: [
      'Forge a frost-tempered blade',
      'Climb to the caldera',
      'Survive the first breath',
      'Slay the wyrm',
    ],
    resetCount: 0,
  },
  {
    id: 'q-smugglers',
    title: 'Lanterns in the Fog',
    region: 'Saltmarsh Coast',
    giver: 'Harbourmaster Idris',
    difficulty: 'normal',
    reward: 150,
    status: 'available',
    steps: ['Watch the pier at midnight', 'Follow the lantern boat', 'Report the hideout'],
    resetCount: 0,
  },
  {
    id: 'q-crypt',
    title: 'Whispers Below',
    region: 'Sunken Catacombs',
    giver: 'Sister Maren',
    difficulty: 'hard',
    reward: 420,
    status: 'active',
    steps: ['Find the catacomb key', 'Light the three braziers', 'Silence the lich'],
    resetCount: 0,
  },
  {
    id: 'q-letter',
    title: 'A Letter for the Queen',
    region: 'Old Capital',
    giver: 'Courier Pell',
    difficulty: 'easy',
    reward: 25,
    status: 'completed',
    steps: ['Pick up the sealed letter', 'Deliver it to the palace'],
    resetCount: 0,
  },
  {
    id: 'q-heist',
    title: 'The Gilded Vault',
    region: 'Old Capital',
    giver: 'The Fox',
    difficulty: 'hard',
    reward: 600,
    status: 'available',
    steps: ['Steal the guard rota', 'Bribe the night watch', 'Crack the vault'],
    resetCount: 0,
  },
]
